name: Build and deploy

on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: 'true'
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2.6.0
      with:
        hugo-version: latest
    - name: Build local ./site
      run: hugo --minify --gc --destination ../public --source ./site --themesDir ../themes --baseURL https://l480.github.io/
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: build
        path: ./public
  deploy:
    needs: build
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: build
          path: ./public
      - uses: peaceiris/actions-gh-pages@v3.9.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          cname: nicoo.org
